version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017/batak_wedding
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: